namespace Eden_World_Maniputor_2._0
{
    public enum Painting
    {
        Unpainted,

        LightRed,
        LightOrange,
        LightYellow,
        LightGreen,
        LightCyan,
        LightBlue,
        LightPurple,
        LightPink,
        White,

        MediumLightRed,
        MediumLightOrange,
        MediumLightYellow,
        MediumLightGreen,
        MediumLightCyan,
        MediumLightBlue,
        MediumLightPurple,
        MediumLightPink,
        MediumLightGray,

        Red,
        Orange,
        Yellow,
        Green,
        Cyan,
        Blue,
        Purple,
        Pink,
        Gray,

        MediumDarkRed,
        MediumDarkOrange,
        MediumDarkYellow,
        MediumDarkGreen,
        MediumDarkCyan,
        MediumDarkBlue,
        MediumDarkPurple,
        MediumDarkPink,
        MediumDarkGray,

        DarkRed,
        DarkOrange,
        DarkYellow,
        DarkGreen,
        DarkCyan,
        DarkBlue,
        DarkPurple,
        DarkPink,
        DarkGray,

        VeryDarkRed,
        VeryDarkOrange,
        VeryDarkYellow,
        VeryDarkGreen,
        VeryDarkCyan,
        VeryDarkBlue,
        VeryDarkPurple,
        VeryDarkPink,
        Black,
    }
}
